name: nes-github-actions
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: prepare software
        run: |
          sudo apt-get update
          sudo apt-get install git make gcc p7zip-full llvm-dev libsdl2-dev -y
          wget https://xmake.io/shget.text -O - | bash -s v2.7.7
          source ~/.xmake/profile
          xrepo update-repo
      - name: build
        run: |
          xmake -y
