name: nes-github-actions
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: prepare software
        run: |
          sudo apt-get update
          sudo apt-get install git make gcc p7zip-full llvm-dev libsdl2-dev -y
          sudo add-apt-repository ppa:xmake-io/xmake -y
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install xmake -y
          xmake update
      - name: build
        run: |
          xmake -y
