
name: linux
run-name: Linux Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'README_zh.md'
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]
jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
          arch: [x86_64]
    runs-on: ${{ matrix.os }}
    concurrency:
        group: ${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: prepare software
        run: |
          sudo apt-get update
          sudo apt-get install git make gcc p7zip-full libsdl2-dev -y
          sudo apt-get upgrade -y
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: build
        run: |
          xmake -v -y
          cp build/linux/${{ matrix.arch }}/release/nes nes-linux-${{ matrix.arch }}.bin

      - uses: actions/upload-artifact@v4
        with:
          name: nes-linux-${{ matrix.arch }}.bin
          path: nes-linux-${{ matrix.arch }}.bin
