
name: Macos
run-name: Macos Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'README_zh.md'
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest]
          arch: [x86_64,arm64]
    runs-on: ${{ matrix.os }}
    concurrency:
        group: ${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: prepare software
        run: |
          brew update
          brew install make gcc sdl2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: build
        run: |
          xmake -y


