
name: Macos
run-name: Macos Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'README_zh.md'
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest]
          arch: [x86_64,arm64]
    runs-on: ${{ matrix.os }}
    concurrency:
        group: ${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: prepare software
        run: |
          brew update
          brew install make gcc sdl2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: build
        run: |
          xmake -v -y
          cp build/macosx/${{ matrix.arch }}/release/nes nes-macos-${{ matrix.arch }}.app

      - uses: actions/upload-artifact@v4
        with:
          name: nes-macos-${{ matrix.arch }}.app
          path: nes-macos-${{ matrix.arch }}.app

        # upload artifacts to latest release
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: Upload artifacts to lastest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nes-macos-${{ matrix.arch }}.app
          asset_name: nes-macos-${{ matrix.arch }}.app
          tag: ${{ steps.previoustag.outputs.tag }}
          overwrite: true

