
name: Macos
run-name: Macos Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
        - '.github/workflows/release.yml'
        - 'docs/**'
        - 'README.md'
        - 'README_zh.md'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest]
          arch: [arm64]
    runs-on: ${{ matrix.os }}
    concurrency:
        group: ${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: prepare software
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew update
          brew install make sdl2 xmake
          xmake update
      - name: build
        run: |
          xrepo update-repo
          xmake -v -y
          cp build/macosx/${{ matrix.arch }}/release/nes nes-macos-${{ matrix.arch }}.AppImage

      - uses: actions/upload-artifact@v4
        with:
          name: nes-macos-${{ matrix.arch }}.AppImage
          path: nes-macos-${{ matrix.arch }}.AppImage
