name: Create Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            name: Release ${{ github.ref }}
            body: |
              [CHANGELOG](https://github.com/Dozingfiretruck/nes/blob/master/docs/CHANGELOG.md#Changelog)
              [更新日志](https://github.com/Dozingfiretruck/nes/blob/master/docs/CHANGELOG.md#更新日志)
            draft: false
            prerelease: false

      - name: test txt
        run: echo ${{ github.sha }} > test.txt

      - name: Publish file to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test.txt
          asset_name: test.txt
          asset_content_type: application/zip
















